package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidades generated by hbm2java
 */
@Entity
@Table(name="cidades"
    ,catalog="pet"
)
public class Cidades  implements java.io.Serializable {


     private Integer codcid;
     private Estados estados;
     private String nomecid;
     private Set <Endereco> enderecos = new HashSet <>(0);

    public Cidades() {
    }

	
    public Cidades(Estados estados, String nomecid) {
        this.estados = estados;
        this.nomecid = nomecid;
    }
    public Cidades(Estados estados, String nomecid, Set enderecos) {
       this.estados = estados;
       this.nomecid = nomecid;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODCID", unique=true, nullable=false)
    public Integer getCodcid() {
        return this.codcid;
    }
    
    public void setCodcid(Integer codcid) {
        this.codcid = codcid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODEST", nullable=false)
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }

    
    @Column(name="NOMECID", nullable=false, length=50)
    public String getNomecid() {
        return this.nomecid;
    }
    
    public void setNomecid(String nomecid) {
        this.nomecid = nomecid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidades")
    public Set <Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }


     @Override
    public String toString() {
        return nomecid;
    }


}


