package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="pet"
)
public class Clientes  implements java.io.Serializable {


     private Integer codcli;
     private String nomecli;
     private String CpfCnpjcli;
     private String rgcli;
     private String telcli;
     private String sexocli;
     private Date nasccli;
     private Set<Animais> animaises = new HashSet<>(0);
     private Set<Endereco> enderecos = new HashSet<>(0);
     private Set<Vendas> vendases = new HashSet<>(0);

    public Clientes() {
    }

	
    public Clientes(String nomecli, String CpfCnpjcli, String sexocli, Date nasccli) {
        this.nomecli = nomecli;
        this.CpfCnpjcli = CpfCnpjcli;
        this.sexocli = sexocli;
        this.nasccli = nasccli;
    }
    public Clientes(String nomecli, String CpfCnpjcli, String rgcli, String telcli, String sexocli, Date nasccli, Set animaises, Set enderecos, Set vendases) {
       this.nomecli = nomecli;
       this.CpfCnpjcli = CpfCnpjcli;
       this.rgcli = rgcli;
       this.telcli = telcli;
       this.sexocli = sexocli;
       this.nasccli = nasccli;
       this.animaises = animaises;
       this.enderecos = enderecos;
       this.vendases = vendases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODCLI", unique=true, nullable=false)
    public Integer getCodcli() {
        return this.codcli;
    }
    
    public void setCodcli(Integer codcli) {
        this.codcli = codcli;
    }

    
    @Column(name="NOMECLI", nullable=false, length=50)
    public String getNomecli() {
        return this.nomecli;
    }
    
    public void setNomecli(String nomecli) {
        this.nomecli = nomecli;
    }

    
    @Column(name="CPFCNPJCLI", nullable=false, length=11)
    public String getCpfCnpjcli() {
        return this.CpfCnpjcli;
    }
    
    public void setCpfCnpjcli(String CpfCnpjcli) {
        this.CpfCnpjcli = CpfCnpjcli;
    }

    
    @Column(name="RGCLI", length=20)
    public String getRgcli() {
        return this.rgcli;
    }
    
    public void setRgcli(String rgcli) {
        this.rgcli = rgcli;
    }

    
    @Column(name="TELCLI", length=14)
    public String getTelcli() {
        return this.telcli;
    }
    
    public void setTelcli(String telcli) {
        this.telcli = telcli;
    }

    
    @Column(name="SEXOCLI", nullable=true, length=10)
    public String getSexocli() {
        return this.sexocli;
    }
    
    public void setSexocli(String sexocli) {
        this.sexocli = sexocli;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NASCCLI", nullable=true, length=10)
    public Date getNasccli() {
        return this.nasccli;
    }
    
    public void setNasccli(Date nasccli) {
        this.nasccli = nasccli;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<Animais> getAnimaises() {
        return this.animaises;
    }
    
    public void setAnimaises(Set animaises) {
        this.animaises = animaises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<Vendas> getVendases() {
        return this.vendases;
    }
    
    public void setVendases(Set vendases) {
        this.vendases = vendases;
    }


 @Override
    public String toString() {
        return nomecli;
       
    }


}


