package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compras generated by hbm2java
 */
@Entity
@Table(name="compras"
    ,catalog="pet"
)
public class Compras  implements java.io.Serializable {


     private Integer codcompra;
     private Fornecedores fornecedores;
     private Float totalcompra;
     private Date datacompra;
     private Date horacompra;
     private Set <RelatamItensCompras> relatamItensComprases = new HashSet<>(0);

    public Compras() {
    }

	
    public Compras(Fornecedores fornecedores, Float totalcompra, Date datacompra, Date horacompra) {
        this.fornecedores = fornecedores;
        this.totalcompra = totalcompra;
        this.datacompra = datacompra;
        this.horacompra = horacompra;
    }
    public Compras(Fornecedores fornecedores, Float totalcompra, Date datacompra, Date horacompra, Set relatamItensComprases) {
       this.fornecedores = fornecedores;
       this.totalcompra = totalcompra;
       this.datacompra = datacompra;
       this.horacompra = horacompra;
       this.relatamItensComprases = relatamItensComprases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODCOMPRA", unique=true, nullable=false)
    public Integer getCodcompra() {
        return this.codcompra;
    }
    
    public void setCodcompra(Integer codcompra) {
        this.codcompra = codcompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODFOR", nullable=false)
    public Fornecedores getFornecedores() {
        return this.fornecedores;
    }
    
    public void setFornecedores(Fornecedores fornecedores) {
        this.fornecedores = fornecedores;
    }

    
    @Column(name="TOTALCOMPRA", nullable=false, precision=9)
    public Float getTotalcompra() {
        return this.totalcompra;
    }
    
    public void setTotalcompra(Float totalcompra) {
        this.totalcompra = totalcompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATACOMPRA", nullable=false, length=10)
    public Date getDatacompra() {
        return this.datacompra;
    }
    
    public void setDatacompra(Date datacompra) {
        this.datacompra = datacompra;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORACOMPRA", nullable=false, length=8)
    public Date getHoracompra() {
        return this.horacompra;
    }
    
    public void setHoracompra(Date horacompra) {
        this.horacompra = horacompra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compras")
    public Set<RelatamItensCompras> getRelatamItensComprases() {
        return this.relatamItensComprases;
    }
    
    public void setRelatamItensComprases(Set relatamItensComprases) {
        this.relatamItensComprases = relatamItensComprases;
    }

    @Override
    public String toString() {
        return fornecedores.getNomefor();
    }




}


