package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cores generated by hbm2java
 */
@Entity
@Table(name="cores"
    ,catalog="pet"
)
public class Cores  implements java.io.Serializable {


     private Integer codcor;
     private String nomecor;
     private Set<Animais> animaises = new HashSet<>(0);

    public Cores() {
    }

	
    public Cores(String nomecor) {
        this.nomecor = nomecor;
    }
    public Cores(String nomecor, Set animaises) {
       this.nomecor = nomecor;
       this.animaises = animaises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODCOR", unique=true, nullable=false)
    public Integer getCodcor() {
        return this.codcor;
    }
    
    public void setCodcor(Integer codcor) {
        this.codcor = codcor;
    }

    
    @Column(name="NOMECOR", nullable=false, length=20)
    public String getNomecor() {
        return this.nomecor;
    }
    
    public void setNomecor(String nomecor) {
        this.nomecor = nomecor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cores")
    public Set<Animais> getAnimaises() {
        return this.animaises;
    }
    
    public void setAnimaises(Set animaises) {
        this.animaises = animaises;
    }


     @Override
    public String toString() {
        return nomecor;
    }


}


