package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,catalog="pet"
)
public class Endereco  implements java.io.Serializable {


     private Integer coded;
     private Cidades cidades;
     private Clientes clientes;
     private Fornecedores fornecedores;
     private String ruaed;
     private String bairroed;
     private String numed;
     private String comped;
     private String ceped;

    public Endereco() {
    }

	
    public Endereco(Cidades cidades, String ruaed, String bairroed) {
        this.cidades = cidades;
        this.ruaed = ruaed;
        this.bairroed = bairroed;
    }
    public Endereco(Cidades cidades, Clientes clientes, Fornecedores fornecedores, String ruaed, String bairroed, String numed, String comped, String ceped) {
       this.cidades = cidades;
       this.clientes = clientes;
       this.fornecedores = fornecedores;
       this.ruaed = ruaed;
       this.bairroed = bairroed;
       this.numed = numed;
       this.comped = comped;
       this.ceped = ceped;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODED", unique=true, nullable=false)
    public Integer getCoded() {
        return this.coded;
    }
    
    public void setCoded(Integer coded) {
        this.coded = coded;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODCID", nullable=false)
    public Cidades getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Cidades cidades) {
        this.cidades = cidades;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODCLI")
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODFOR")
    public Fornecedores getFornecedores() {
        return this.fornecedores;
    }
    
    public void setFornecedores(Fornecedores fornecedores) {
        this.fornecedores = fornecedores;
    }

    
    @Column(name="RUAED", nullable=false, length=50)
    public String getRuaed() {
        return this.ruaed;
    }
    
    public void setRuaed(String ruaed) {
        this.ruaed = ruaed;
    }

    
    @Column(name="BAIRROED", nullable=false, length=50)
    public String getBairroed() {
        return this.bairroed;
    }
    
    public void setBairroed(String bairroed) {
        this.bairroed = bairroed;
    }

    
    @Column(name="NUMED", length=10)
    public String getNumed() {
        return this.numed;
    }
    
    public void setNumed(String numed) {
        this.numed = numed;
    }

    
    @Column(name="COMPED", length=50)
    public String getComped() {
        return this.comped;
    }
    
    public void setComped(String comped) {
        this.comped = comped;
    }

    
    @Column(name="CEPED", length=8)
    public String getCeped() {
        return this.ceped;
    }
    
    public void setCeped(String ceped) {
        this.ceped = ceped;
    }

  




}


