package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Especies generated by hbm2java
 */
@Entity
@Table(name="especies"
    ,catalog="pet"
)
public class Especies  implements java.io.Serializable {


     private Integer codesp;
     private String nomeesp;
     private Set <Racas>racases = new HashSet<>(0);

    public Especies() {
    }

	
    public Especies(String nomeesp) {
        this.nomeesp = nomeesp;
    }
    public Especies(String nomeesp, Set racases) {
       this.nomeesp = nomeesp;
       this.racases = racases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODESP", unique=true, nullable=false)
    public Integer getCodesp() {
        return this.codesp;
    }
    
    public void setCodesp(Integer codesp) {
        this.codesp = codesp;
    }

    
    @Column(name="NOMEESP", nullable=false, length=50)
    public String getNomeesp() {
        return this.nomeesp;
    }
    
    public void setNomeesp(String nomeesp) {
        this.nomeesp = nomeesp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="especies")
    public Set<Racas> getRacases() {
        return this.racases;
    }
    
    public void setRacases(Set racases) {
        this.racases = racases;
    }


     @Override
    public String toString() {
        return nomeesp;
    }


}


