package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name="estados"
    ,catalog="pet"
)
public class Estados  implements java.io.Serializable {


     private Integer codest;
     private String siglaest;
     private Set<Cidades> cidadeses = new HashSet<>(0);

    public Estados() {
    }

	
    public Estados(String siglaest) {
        this.siglaest = siglaest;
    }
    public Estados(String siglaest, Set cidadeses) {
       this.siglaest = siglaest;
       this.cidadeses = cidadeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODEST", unique=true, nullable=false)
    public Integer getCodest() {
        return this.codest;
    }
    
    public void setCodest(Integer codest) {
        this.codest = codest;
    }

    
    @Column(name="SIGLAEST", nullable=false, length=2)
    public String getSiglaest() {
        return this.siglaest;
    }
    
    public void setSiglaest(String siglaest) {
        this.siglaest = siglaest;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Cidades> getCidadeses() {
        return this.cidadeses;
    }
    
    public void setCidadeses(Set cidadeses) {
        this.cidadeses = cidadeses;
    }

     @Override
    public String toString() {
        return siglaest;
    }



}


