package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedores generated by hbm2java
 */
@Entity
@Table(name="fornecedores"
    ,catalog="pet"
)
public class Fornecedores  implements java.io.Serializable {


     private Integer codfor;
     private String nomefor;
     private String cpfCnpjfor;
     private String rgfor;
     private String telfor;
     private Set<Compras> comprases = new HashSet<>(0);
     private Set<Endereco> enderecos = new HashSet<>(0);

    public Fornecedores() {
    }

	
    public Fornecedores(String nomefor, String cpfCnpjfor) {
        this.nomefor = nomefor;
        this.cpfCnpjfor = cpfCnpjfor;
    }
    public Fornecedores(Set produtosServicoses ,String nomefor, String cpfCnpjfor, String rgfor, String telfor, Set comprases, Set enderecos) {
       this.nomefor = nomefor;
       this.cpfCnpjfor = cpfCnpjfor;
       this.rgfor = rgfor;
       this.telfor = telfor;
       this.comprases = comprases;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODFOR", unique=true, nullable=false)
    public Integer getCodfor() {
        return this.codfor;
    }
    
    public void setCodfor(Integer codfor) {
        this.codfor = codfor;
    }

    
    @Column(name="NOMEFOR", nullable=false, length=50)
    public String getNomefor() {
        return this.nomefor;
    }
    
    public void setNomefor(String nomefor) {
        this.nomefor = nomefor;
    }

    
    @Column(name="CPF_CNPJFOR", length=20)
    public String getCpfCnpjfor() {
        return this.cpfCnpjfor;
    }
    
    public void setCpfCnpjfor(String cpfCnpjfor) {
        this.cpfCnpjfor = cpfCnpjfor;
    }

    
    @Column(name="RGFOR", length=14)
    public String getRgfor() {
        return this.rgfor;
    }
    
    public void setRgfor(String rgfor) {
        this.rgfor = rgfor;
    }

    
    @Column(name="TELFOR", length=14)
    public String getTelfor() {
        return this.telfor;
    }
    
    public void setTelfor(String telfor) {
        this.telfor = telfor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedores")
    public Set<Compras> getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedores")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }



    @Override
    public String toString() {
        return getNomefor();
    }




}


