package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatamItensVendas generated by hbm2java
 */
@Entity
@Table(name = "relatam_itens_vendas",
         catalog = "pet"
)
public class RelatamItensVendas implements java.io.Serializable {

    private Integer coditemV;
    private ProdutosServicos produtosServicos;
    private Vendas vendas;
    private Animais animais;
    private Float qtditemV;
    private Float precoitemV;
    private Float totalitemV;

    public RelatamItensVendas() {
    }

    public RelatamItensVendas(Animais animais, ProdutosServicos produtosServicos, Vendas vendas, Float qtditemV, Float precoitemV, Float totalitemV) {
        this.produtosServicos = produtosServicos;
        this.animais = animais;
        this.vendas = vendas;
        this.qtditemV = qtditemV;
        this.precoitemV = precoitemV;
        this.totalitemV = totalitemV;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CODITEM_V", unique = true, nullable = false)
    public Integer getCoditemV() {
        return this.coditemV;
    }

    public void setCoditemV(Integer coditemV) {
        this.coditemV = coditemV;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODPROD", nullable = false)
    public ProdutosServicos getProdutosServicos() {
        return this.produtosServicos;
    }

    public void setProdutosServicos(ProdutosServicos produtosServicos) {
        this.produtosServicos = produtosServicos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODVENDA", nullable = false)
    public Vendas getVendas() {
        return this.vendas;
    }

    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODANI")
    public Animais getAnimais() {
        return this.animais;
    }

    public void setAnimais(Animais animais) {
        this.animais = animais;
    }

    @Column(name = "QTDITEM_V", nullable = false, precision = 9, scale = 3)
    public Float getQtditemV() {
        return this.qtditemV;
    }

    public void setQtditemV(Float qtditemV) {
        this.qtditemV = qtditemV;
    }

    @Column(name = "PRECOITEM_V", nullable = false, precision = 9)
    public Float getPrecoitemV() {
        return this.precoitemV;
    }

    public void setPrecoitemV(Float precoitemV) {
        this.precoitemV = precoitemV;
    }

    @Column(name = "TOTALITEM_V", nullable = false, precision = 9)
    public Float getTotalitemV() {
        return this.totalitemV;
    }

    public void setTotalitemV(Float totalitemV) {
        this.totalitemV = totalitemV;
    }
   
     
}
