package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatamItensCompras generated by hbm2java
 */
@Entity
@Table(name="relatam_itens_compras"
    ,catalog="pet"
)
public class RelatamItensCompras  implements java.io.Serializable {


     private Integer coditemC;
     private Compras compras;
     private ProdutosServicos produtosServicos;
     private Float qtditemC;
     private Float precoitemC;
     private Float totalitemC;

    public RelatamItensCompras() {
    }

    public RelatamItensCompras(Compras compras, ProdutosServicos produtosServicos, Float qtditemC, Float precoitemC, Float totalitemC) {
       this.compras = compras;
       this.produtosServicos = produtosServicos;
       this.qtditemC = qtditemC;
       this.precoitemC = precoitemC;
       this.totalitemC = totalitemC;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODITEM_C", unique=true, nullable=false)
    public Integer getCoditemC() {
        return this.coditemC;
    }
    
    public void setCoditemC(Integer coditemC) {
        this.coditemC = coditemC;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODCOMPRA", nullable=false)
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODPROD", nullable=false)
    public ProdutosServicos getProdutosServicos() {
        return this.produtosServicos;
    }
    
    public void setProdutosServicos(ProdutosServicos produtosServicos) {
        this.produtosServicos = produtosServicos;
    }

    
    @Column(name="QTDITEM_C", nullable=false, precision=9, scale=3)
    public Float getQtditemC() {
        return this.qtditemC;
    }
    
    public void setQtditemC(Float qtditemC) {
        this.qtditemC = qtditemC;
    }

    
    @Column(name="PRECOITEM_C", nullable=false, precision=9)
    public Float getPrecoitemC() {
        return this.precoitemC;
    }
    
    public void setPrecoitemC(Float precoitemC) {
        this.precoitemC = precoitemC;
    }

    
    @Column(name="TOTALITEM_C", nullable=false, precision=9)
    public Float getTotalitemC() {
        return this.totalitemC;
    }
    
    public void setTotalitemC(Float totalitemC) {
        this.totalitemC = totalitemC;
    }




}


