package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAcesso generated by hbm2java
 */
@Entity
@Table(name = "tipo_acesso",
         catalog = "pet"
)
public class TipoAcesso implements java.io.Serializable {

    private Integer codacess;
    private String nomeacess;
    private Set<Usuarios> usuarioses = new HashSet<>(0);

    public TipoAcesso() {
    }

    public TipoAcesso(String nomeacess) {
        this.nomeacess = nomeacess;
    }

    public TipoAcesso(String nomeacess, Set usuarioses) {
        this.nomeacess = nomeacess;
        this.usuarioses = usuarioses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "CODACESS", unique = true, nullable = false)
    public Integer getCodacess() {
        return this.codacess;
    }

    public void setCodacess(Integer codacess) {
        this.codacess = codacess;
    }

    @Column(name = "NOMEACESS", nullable = false, length = 10)
    public String getNomeacess() {
        return this.nomeacess;
    }

    public void setNomeacess(String nomeacess) {
        this.nomeacess = nomeacess;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAcesso")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

    @Override
    public String toString() {
        return nomeacess;
    }

}
