package _models;
// Generated 12/05/2018 23:53:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidades generated by hbm2java
 */
@Entity
@Table(name="unidades"
    ,catalog="pet"
)
public class Unidades  implements java.io.Serializable {


     private Integer coduni;
     private String tipouni;
     private Set<ProdutosServicos> produtosServicoses = new HashSet<>(0);

    public Unidades() {
    }

	
    public Unidades(String tipouni) {
        this.tipouni = tipouni;
    }
    public Unidades(String tipouni, Set produtosServicoses) {
       this.tipouni = tipouni;
       this.produtosServicoses = produtosServicoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODUNI", unique=true, nullable=false)
    public Integer getCoduni() {
        return this.coduni;
    }
    
    public void setCoduni(Integer coduni) {
        this.coduni = coduni;
    }

    
    @Column(name="TIPOUNI", nullable=false, length=10)
    public String getTipouni() {
        return this.tipouni;
    }
    
    public void setTipouni(String tipouni) {
        this.tipouni = tipouni;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidades")
    public Set<ProdutosServicos> getProdutosServicoses() {
        return this.produtosServicoses;
    }
    
    public void setProdutosServicoses(Set produtosServicoses) {
        this.produtosServicoses = produtosServicoses;
    }

    @Override
    public String toString() {
        return tipouni;
    }



}


